//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CabinetInventoryObject
    {
        public int ID { get; set; }
        public int IDInventoryObject { get; set; }
        public int IDCabinet { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Cabinet Cabinet { get; set; }
        public virtual InventoryObject InventoryObject { get; set; }
    }
}
