//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbMobileCenterEntities : DbContext
    {
        public dbMobileCenterEntities()
            : base("name=dbMobileCenterEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Abonent> Abonent { get; set; }
        public virtual DbSet<ATC> ATC { get; set; }
        public virtual DbSet<City> City { get; set; }
        public virtual DbSet<CityDisctict> CityDisctict { get; set; }
        public virtual DbSet<Disctrict> Disctrict { get; set; }
        public virtual DbSet<Sim> Sim { get; set; }
        public virtual DbSet<SimATCAbonent> SimATCAbonent { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
