//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SimATCAbonent
    {
        public int ID { get; set; }
        public int IDSim { get; set; }
        public int IDATC { get; set; }
        public int IDAbonent { get; set; }
    
        public virtual Abonent Abonent { get; set; }
        public virtual ATC ATC { get; set; }
        public virtual Sim Sim { get; set; }
        public virtual ATC ATC1 { get; set; }
    }
}
