//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArhiveInventoryObject
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string InventoryNumber { get; set; }
        public System.DateTime CommissioningDate { get; set; }
        public string DocumentationPath { get; set; }
        public string IDType { get; set; }
        public string IDSubType { get; set; }
        public int LifeTime { get; set; }
        public string IDInvoce { get; set; }
        public string IDCurrentStatus { get; set; }
        public decimal Amount { get; set; }
        public string IDEmployee { get; set; }
        public string IDInventoryObjectDetail { get; set; }
        public System.DateTime Date { get; set; }
    }
}
